"""Added None type to sent_from_location and sent_to_location in CaseFileTransaction

Revision ID: 43131950cd4b
Revises: c8a083dbafde
Create Date: 2026-08-13 14:40:40.372309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '43131950cd4b'
down_revision: Union[str, Sequence[str], None] = 'c8a083dbafde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casefiletransaction', 'sent_from_location',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('casefiletransaction', 'sent_to_location',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casefiletransaction', 'sent_to_location',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('casefiletransaction', 'sent_from_location',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
