"""In CaseFileTransaction, changed 'record_id' to 'id'

Revision ID: 722c8f1bc434
Revises: 6822dab5f816
Create Date: 2026-08-10 11:24:41.373515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '722c8f1bc434'
down_revision: Union[str, Sequence[str], None] = '6822dab5f816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casefiletransaction', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('casefiletransaction', 'record_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casefiletransaction', sa.Column('record_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('casefiletransaction', 'id')
    # ### end Alembic commands ###
