"""CaseFileTransaction id PK default

Revision ID: 9beb2c5f2fd2
Revises: 73e0bb084533
Create Date: 2026-08-13 15:01:17.524518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9beb2c5f2fd2'
down_revision: Union[str, Sequence[str], None] = '73e0bb084533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
