"""Add 'status' column to CaseFileTransaction table

Revision ID: c8a083dbafde
Revises: 722c8f1bc434
Create Date: 2026-08-11 14:58:47.229640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c8a083dbafde'
down_revision: Union[str, Sequence[str], None] = '722c8f1bc434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casefiletransaction', sa.Column('status', sa.Enum('pending', 'completed', name='transactionstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casefiletransaction', 'status')
    # ### end Alembic commands ###
